apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm
spec:
  selector:
    matchLabels:
      app: farm
  template:
    metadata:
      labels:
        app: farm
    spec:
      containers:
        - name: farm
          image: amrelzahar/node-farm:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
